import { getUserId } from "./auth";
import { supabase } from "./supabase";

// Backed by the `notes` table (supabase/migrations/0008_notes.sql).

export type Note = {
  id: string;
  text: string;
  color: string;
  textColor: string;
  pinned: boolean;
  createdAt: number;
  autoGenerated: boolean;
};

type NoteRow = {
  id: string;
  text: string;
  color: string;
  text_color: string;
  pinned: boolean;
  created_at: string;
  auto_generated: boolean;
};

function fromRow(row: NoteRow): Note {
  return {
    id: row.id,
    text: row.text,
    color: row.color,
    textColor: row.text_color,
    pinned: row.pinned,
    createdAt: new Date(row.created_at).getTime(),
    autoGenerated: row.auto_generated,
  };
}

// Card backgrounds, per the Figma notes-page mock — includes #ffb876, a
// lighter orange that mock introduced alongside the app's existing palette.
// Each background has its own curated list of legible text colors (the mock
// itself pairs e.g. orange bg with dark-pink text, pink bg with orange text
// — text color isn't just always cream) — a random bg then a random text
// color from its list keeps every combination readable.
const CARD_TEXT_OPTIONS: Record<string, string[]> = {
  "#ffb876": ["#e47083", "#89b8c2", "#fff7e7", "#000000"],
  "#ffcc7d": ["#fff7e7", "#e47083", "#89b8c2"],
  "#a8bf89": ["#fff7e7", "#000000", "#e47083"],
  "#f49aa3": ["#ffcc7d", "#fff7e7", "#e47083", "#89b8c2"],
  "#e47083": ["#fff7e7", "#ffcc7d"],
  "#89b8c2": ["#fff7e7", "#ffcc7d"],
  "#fff7e7": ["#000000", "#e47083", "#89b8c2", "#a8bf89"],
};
const CARD_COLORS = Object.keys(CARD_TEXT_OPTIONS);

// Seeded once on first launch so the feed isn't empty before the user has
// written anything themselves — a handful of app-authored, encouraging notes
// mixed in with whatever the user adds later.
const SEED_MESSAGES = [
  "You're doing amazing, keep going!",
  "One day at a time.",
  "Your body is capable of incredible things.",
  "Small steps still count.",
  "Be gentle with yourself today.",
  "You showed up today — that's enough.",
  "Progress isn't always visible, but it's happening.",
  "Take a deep breath. You've got this.",
  "Celebrate the little wins.",
  "You are exactly where you need to be.",
];

function randomColorPair() {
  const bg = CARD_COLORS[Math.floor(Math.random() * CARD_COLORS.length)];
  const textOptions = CARD_TEXT_OPTIONS[bg];
  const text = textOptions[Math.floor(Math.random() * textOptions.length)];
  return { bg, text };
}

function pickRandomSeedMessages(count: number): string[] {
  const pool = [...SEED_MESSAGES];
  const picked: string[] = [];
  while (picked.length < count && pool.length > 0) {
    const i = Math.floor(Math.random() * pool.length);
    picked.push(pool.splice(i, 1)[0]);
  }
  return picked;
}

export async function listNotes(): Promise<Note[]> {
  const { data, error } = await supabase
    .from("notes")
    .select("*")
    .order("created_at", { ascending: false });
  if (error) throw new Error(error.message);
  let notes = (data as NoteRow[]).map(fromRow);

  if (notes.length === 0) {
    const userId = await getUserId();
    if (!userId) throw new Error("You're not signed in.");
    const seedRows = pickRandomSeedMessages(6).map((text) => {
      const { bg, text: textColor } = randomColorPair();
      return { user_id: userId, text, color: bg, text_color: textColor, auto_generated: true };
    });
    const { data: inserted, error: insertError } = await supabase.from("notes").insert(seedRows).select();
    if (insertError) throw new Error(insertError.message);
    notes = (inserted as NoteRow[]).map(fromRow).sort((a, b) => b.createdAt - a.createdAt);
  }

  return notes;
}

export async function addNote(text: string): Promise<Note> {
  const userId = await getUserId();
  if (!userId) throw new Error("You're not signed in.");
  const { bg, text: textColor } = randomColorPair();

  const { data, error } = await supabase
    .from("notes")
    .insert({ user_id: userId, text, color: bg, text_color: textColor, auto_generated: false })
    .select()
    .single();
  if (error) throw new Error(error.message);
  return fromRow(data as NoteRow);
}

export async function updateNoteText(id: string, text: string): Promise<Note> {
  const { data, error } = await supabase.from("notes").update({ text }).eq("id", id).select().maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error("Note not found.");
  return fromRow(data as NoteRow);
}

export async function deleteNote(id: string): Promise<void> {
  const { error } = await supabase.from("notes").delete().eq("id", id);
  if (error) throw new Error(error.message);
}

export async function togglePin(id: string): Promise<Note> {
  const { data: current, error: fetchError } = await supabase
    .from("notes")
    .select("pinned")
    .eq("id", id)
    .maybeSingle();
  if (fetchError) throw new Error(fetchError.message);
  if (!current) throw new Error("Note not found.");

  const { data, error } = await supabase
    .from("notes")
    .update({ pinned: !current.pinned })
    .eq("id", id)
    .select()
    .single();
  if (error) throw new Error(error.message);
  return fromRow(data as NoteRow);
}
