import AsyncStorage from "@react-native-async-storage/async-storage";

// Local-only persistence, same rationale as lib/cycles_api.ts — no backend
// for notes yet, and Supabase auth is currently bypassed app-wide.
const STORAGE_KEY = "@pcos/notes";

export type Note = {
  id: string;
  text: string;
  color: string;
  textColor: string;
  pinned: boolean;
  createdAt: number;
  autoGenerated: boolean;
};

// Card backgrounds, per the Figma notes-page mock — includes #ffb876, a
// lighter orange that mock introduced alongside the app's existing palette.
// Each background has its own curated list of legible text colors (the mock
// itself pairs e.g. orange bg with dark-pink text, pink bg with orange text
// — text color isn't just always cream) — a random bg then a random text
// color from its list keeps every combination readable.
const CARD_TEXT_OPTIONS: Record<string, string[]> = {
  "#ffb876": ["#e47083", "#89b8c2", "#fff7e7", "#000000"],
  "#ffcc7d": ["#fff7e7", "#e47083", "#89b8c2"],
  "#a8bf89": ["#fff7e7", "#000000", "#e47083"],
  "#f49aa3": ["#ffcc7d", "#fff7e7", "#e47083", "#89b8c2"],
  "#e47083": ["#fff7e7", "#ffcc7d"],
  "#89b8c2": ["#fff7e7", "#ffcc7d"],
  "#fff7e7": ["#000000", "#e47083", "#89b8c2", "#a8bf89"],
};
const CARD_COLORS = Object.keys(CARD_TEXT_OPTIONS);

// Seeded once on first launch so the feed isn't empty before the user has
// written anything themselves — a handful of app-authored, encouraging notes
// mixed in with whatever the user adds later.
const SEED_MESSAGES = [
  "You're doing amazing, keep going!",
  "One day at a time.",
  "Your body is capable of incredible things.",
  "Small steps still count.",
  "Be gentle with yourself today.",
  "You showed up today — that's enough.",
  "Progress isn't always visible, but it's happening.",
  "Take a deep breath. You've got this.",
  "Celebrate the little wins.",
  "You are exactly where you need to be.",
];

function randomColorPair() {
  const bg = CARD_COLORS[Math.floor(Math.random() * CARD_COLORS.length)];
  const textOptions = CARD_TEXT_OPTIONS[bg];
  const text = textOptions[Math.floor(Math.random() * textOptions.length)];
  return { bg, text };
}

function pickRandomSeedMessages(count: number): string[] {
  const pool = [...SEED_MESSAGES];
  const picked: string[] = [];
  while (picked.length < count && pool.length > 0) {
    const i = Math.floor(Math.random() * pool.length);
    picked.push(pool.splice(i, 1)[0]);
  }
  return picked;
}

function makeNote(text: string, autoGenerated: boolean): Note {
  const { bg, text: textColor } = randomColorPair();
  return {
    // Date.now() alone can collide when several notes are created in the
    // same synchronous batch (e.g. seeding) — the random suffix keeps ids
    // unique in that case.
    id: `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`,
    text,
    color: bg,
    textColor,
    pinned: false,
    createdAt: Date.now(),
    autoGenerated,
  };
}

async function readAll(): Promise<Note[]> {
  const raw = await AsyncStorage.getItem(STORAGE_KEY);
  if (!raw) return [];
  try {
    return JSON.parse(raw) as Note[];
  } catch {
    return [];
  }
}

async function writeAll(notes: Note[]): Promise<void> {
  await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(notes));
}

export async function listNotes(): Promise<Note[]> {
  let notes = await readAll();
  if (notes.length === 0) {
    const seeded = pickRandomSeedMessages(6).map((msg) => makeNote(msg, true));
    await writeAll(seeded);
    notes = seeded;
  }
  return [...notes].sort((a, b) => b.createdAt - a.createdAt);
}

export async function addNote(text: string): Promise<Note> {
  const notes = await readAll();
  const note = makeNote(text, false);
  await writeAll([note, ...notes]);
  return note;
}

export async function updateNoteText(id: string, text: string): Promise<Note> {
  const notes = await readAll();
  const target = notes.find((n) => n.id === id);
  if (!target) throw new Error("Note not found.");
  const updated: Note = { ...target, text };
  await writeAll(notes.map((n) => (n.id === id ? updated : n)));
  return updated;
}

export async function deleteNote(id: string): Promise<void> {
  const notes = await readAll();
  await writeAll(notes.filter((n) => n.id !== id));
}

export async function togglePin(id: string): Promise<Note> {
  const notes = await readAll();
  const target = notes.find((n) => n.id === id);
  if (!target) throw new Error("Note not found.");
  const updated: Note = { ...target, pinned: !target.pinned };
  await writeAll(notes.map((n) => (n.id === id ? updated : n)));
  return updated;
}
